--THỐNG KÊ SỐ LƯỢNG BÁN HÀNG TRÊN MỐI NHÂN VIÊN
use BikeStores
--CỘT: SL BÁN HÀNG
--BẢNG: SALES.ORDER
--ĐK: 0 CÓ
--(THEO NHÂN VIÊN)
SELECT COUNT(ORDER_ID) AS 'SỐ LƯỢNG BÁN HÀNG', 
       O.STAFF_ID AS 'MÃ NHÂN VIÊN', 
       S.last_name, 
       S.first_name
FROM SALES.ORDERS O JOIN SALES.STAFFS S ON O.STAFF_ID = S.STAFF_ID
GROUP BY O.STAFF_ID, S.last_name, S.first_name


-- TỔNG TIỀN HÀNG ĐÃ BÁN MỖI CỬA HÀNG
--CỘT: tên cửa hàng, tổng tiền hàng
--BẢNG: SALE.ORDERS, SALE.STORES
--ĐK: 0 CÓ
 SELECT SUM(QUANTITY),S.STORE_NAME
 FROM SALES.ORDERS O	JOIN SALES.STORES S ON S.STORE_ID = O.STORE_ID
						JOIN SALES.ORDER_ITEMS I ON O.ORDER_ID=I.ORDER_ID
 GROUP BY S.STORE_NAME